class allcountries {
  static List<String> countries_new = [
    '🇦🇺 Australia',
    '🇦🇹 Austria',
    '🇧🇪 Belgium',
    '🇧🇷 Brazil',
    '🇨🇦 Canada',
    '🇨🇱 Chile',
    '🇨🇳 China',
    '🇨🇴 Colombia',
    '🇨🇷 Costa Rica',
    '🇭🇷 Croatia',
    '🇨🇾 Cyprus',
    '🇨🇿 Czech Republic',
    '🇩🇰 Denmark',
    '🇪🇨 Ecuador',
    '🇪🇬 Egypt',
    '🇸🇻 El Salvador',
    '🇪🇪 Estonia',
    '🇫🇮 Finland',
    '🇫🇷 France',
    '🇬🇪 Georgia',
    '🇩🇪 Germany',
    '🇬🇷 Greece',
    '🇬🇹 Guatemala',
    '🇭🇳 Honduras',
    '🇭🇰 Hong Kong',
    '🇭🇺 Hungary',
    '🇮🇸 Iceland',
    '🇮🇳 India',
    '🇮🇩 Indonesia',
    '🇮🇪 Ireland',
    '🇮🇹 Italy',
    '🇯🇵 Japan',
    '🇯🇴 Jordan',
    '🇰🇿 Kazakhstan',
    '🇰🇪 Kenya',
    '🇽🇰 Kosovo',
    '🇰🇼 Kuwait',
    '🇰🇬 Kyrgyzstan',
    '🇱🇻 Latvia',
    '🇱🇧 Lebanon',
    '🇱🇹 Lithuania',
    '🇱🇺 Luxembourg',
    '🇲🇾 Malaysia',
    '🇲🇹 Malta',
    '🇲🇽 Mexico',
    '🇲🇩 Moldova',
    '🇲🇪 Montenegro',
    '🇲🇦 Morocco',
    '🇳🇱 Netherlands',
    '🇳🇿 New Zealand',
    '🇳🇮 Nicaragua',
    '🇳🇬 Nigeria',
    '🇲🇰 North Macedonia',
    '🇳🇴 Norway',
    '🇴🇲 Oman',
    '🇵🇰 Pakistan',
    '🇵🇸 Palestine',
    '🇵🇦 Panama',
    '🇵🇾 Paraguay',
    '🇵🇪 Peru',
    '🇵🇭 Philippines',
    '🇵🇱 Poland',
    '🇵🇹 Portugal',
    '🇶🇦 Qatar',
    '🇷🇴 Romania',
    '🇷🇺 Russia',
    '🇸🇦 Saudi Arabia',
    '🇸🇪 Sweden',
    '🇸🇬 Singapore',
    '🇸🇰 Slovakia',
    '🇸🇮 Slovenia',
    '🇿🇦 South Africa',
    '🇰🇷 South Korea',
    '🇪🇸 Spain',
    '🇱🇰 Sri Lanka',
    '🇸🇪 Sweden',
    '🇨🇭 Switzerland',
    '🇹🇼 Taiwan',
    '🇹🇭 Thailand',
    '🇹🇳 Tunisia',
    '🇹🇷 Turkey',
    '🇺🇦 Ukraine',
    '🇦🇪 United Arab Emirates',
    '🇬🇧 United Kingdom',
    '🇺🇸 United States',
    '🇺🇾 Uruguay',
    '🇺🇿 Uzbekistan',
    '🇻🇪 Venezuela',
    '🇻🇳 Vietnam',
    '🇾🇪 Yemen', 
    '🇿🇼 Zimbabwe',
  ];
  static final Map<String, String> emojiToCountry = {
    '🇦🇺': 'Australia',
    '🇦🇹': 'Austria',
    '🇧🇪': 'Belgium',
    '🇧🇷': 'Brazil',
    '🇨🇦': 'Canada',
    '🇨🇱': 'Chile',
    '🇨🇳': 'China',
    '🇨🇴': 'Colombia',
    '🇨🇷': 'Costa Rica',
    '🇭🇷': 'Croatia',
    '🇨🇾': 'Cyprus',
    '🇨🇿': 'Czech Republic',
    '🇩🇰': 'Denmark',
    '🇪🇨': 'Ecuador',
    '🇪🇬': 'Egypt',
    '🇸🇻': 'El Salvador',
    '🇪🇪': 'Estonia',
    '🇫🇮': 'Finland',
    '🇫🇷': 'France',
    '🇬🇪': 'Georgia',
    '🇩🇪': 'Germany',
    '🇬🇷': 'Greece',
    '🇬🇹': 'Guatemala',
    '🇭🇳': 'Honduras',
    '🇭🇰': 'Hong Kong',
    '🇭🇺': 'Hungary',
    '🇮🇸': 'Iceland',
    '🇮🇳': 'India',
    '🇮🇩': 'Indonesia',
    '🇮🇪': 'Ireland',
    '🇮🇹': 'Italy',
    '🇯🇵': 'Japan',
    '🇯🇴': 'Jordan',
    '🇰🇿': 'Kazakhstan',
    '🇰🇪': 'Kenya',
    '🇽🇰': 'Kosovo',
    '🇰🇼': 'Kuwait',
    '🇰🇬': 'Kyrgyzstan',
    '🇱🇻': 'Latvia',
    '🇱🇧': 'Lebanon',
    '🇱🇹': 'Lithuania',
    '🇱🇺': 'Luxembourg',
    '🇲🇾': 'Malaysia',
    '🇲🇹': 'Malta',
    '🇲🇽': 'Mexico',
    '🇲🇩': 'Moldova',
    '🇲🇪': 'Montenegro',
    '🇲🇦': 'Morocco',
    '🇳🇱': 'Netherlands',
    '🇳🇿': 'New Zealand',
    '🇳🇮': 'Nicaragua',
    '🇳🇬': 'Nigeria',
    '🇲🇰': 'North Macedonia',
    '🇳🇴': 'Norway',
    '🇴🇲': 'Oman',
    '🇵🇰': 'Pakistan',
    '🇵🇸' : 'Palestine',
    '🇵🇦': 'Panama',
    '🇵🇾': 'Paraguay',
    '🇵🇪': 'Peru',
    '🇵🇭': 'Philippines',
    '🇵🇱': 'Poland',
    '🇵🇹': 'Portugal',
    '🇶🇦': 'Qatar',
    '🇷🇴': 'Romania',
    '🇷🇺': 'Russia',
    '🇸🇦': 'Saudi Arabia',
    '🇷🇸': 'Serbia',
    '🇸🇬': 'Singapore',
    '🇸🇰': 'Slovakia',
    '🇸🇮': 'Slovenia',
    '🇿🇦': 'South Africa',
    '🇰🇷': 'South Korea',
    '🇪🇸': 'Spain',
    '🇱🇰': 'Sri Lanka',
    '🇸🇪': 'Sweden',
    '🇨🇭': 'Switzerland',
    '🇹🇼': 'Taiwan',
    '🇹🇭': 'Thailand',
    '🇹🇳': 'Tunisia',
    '🇹🇷': 'Turkey',
    '🇺🇦': 'Ukraine',
    '🇦🇪': 'United Arab Emirates',
    '🇬🇧': 'United Kingdom',
    '🇺🇸': 'United States',
    '🇺🇾': 'Uruguay',
    '🇺🇿': 'Uzbekistan',
    '🇻🇪': 'Venezuela',
    '🇻🇳': 'Vietnam',
    '🇾🇪': 'Yemen',
    '🇿🇼': 'Zimbabwe',
  };


static List<Map<String, dynamic>> countries = [
    {"emoji": "🇦🇺", "countryName": "Australia"},
    {"emoji": "🇦🇹", "countryName": "Austria"},
    {"emoji": "🇧🇪", "countryName": "Belgium"},
    {"emoji": "🇧🇷", "countryName": "Brazil"},
    {"emoji": "🇨🇦", "countryName": "Canada"},
    {"emoji": "🇨🇱", "countryName": "Chile"},
    {"emoji": "🇨🇳", "countryName": "China"},
    {"emoji": "🇨🇴", "countryName": "Colombia"},
    {"emoji": "🇨🇷", "countryName": "Costa Rica"},
    {"emoji": "🇭🇷", "countryName": "Croatia"},
    {"emoji": "🇨🇾", "countryName": "Cyprus"},
    {"emoji": "🇨🇿", "countryName": "Czech Republic"},
    {"emoji": "🇩🇰", "countryName": "Denmark"},
    {"emoji": "🇪🇨", "countryName": "Ecuador"},
    {"emoji": "🇪🇬", "countryName": "Egypt"},
    {"emoji": "🇸🇻", "countryName": "El Salvador"},
    {"emoji": "🇪🇪", "countryName": "Estonia"},
    {"emoji": "🇫🇮", "countryName": "Finland"},
    {"emoji": "🇫🇷", "countryName": "France"},
    {"emoji": "🇬🇪", "countryName": "Georgia"},
    {"emoji": "🇩🇪", "countryName": "Germany"},
    {"emoji": "🇬🇷", "countryName": "Greece"},
    {"emoji": "🇬🇹", "countryName": "Guatemala"},
    {"emoji": "🇭🇳", "countryName": "Honduras"},
    {"emoji": "🇭🇰", "countryName": "Hong Kong"},
    {"emoji": "🇭🇺", "countryName": "Hungary"},
    {"emoji": "🇮🇸", "countryName": "Iceland"},
    {"emoji": "🇮🇳", "countryName": "India"},
    {"emoji": "🇮🇩", "countryName": "Indonesia"},
    {"emoji": "🇮🇪", "countryName": "Ireland"},
    {"emoji": "🇮🇹", "countryName": "Italy"},
    {"emoji": "🇯🇵", "countryName": "Japan"},
    {"emoji": "🇯🇴", "countryName": "Jordan"},
    {"emoji": "🇰🇿", "countryName": "Kazakhstan"},
    {"emoji": "🇰🇪", "countryName": "Kenya"},
    {"emoji": "🇽🇰", "countryName": "Kosovo"},
    {"emoji": "🇰🇼", "countryName": "Kuwait"},
    {"emoji": "🇰🇬", "countryName": "Kyrgyzstan"},
    {"emoji": "🇱🇻", "countryName": "Latvia"},
    {"emoji": "🇱🇧", "countryName": "Lebanon"},
    {"emoji": "🇱🇹", "countryName": "Lithuania"},
    {"emoji": "🇱🇺", "countryName": "Luxembourg"},
    {"emoji": "🇲🇾", "countryName": "Malaysia"},
    {"emoji": "🇲🇹", "countryName": "Malta"},
    {"emoji": "🇲🇽", "countryName": "Mexico"},
    {"emoji": "🇲🇩", "countryName": "Moldova"},
    {"emoji": "🇲🇪", "countryName": "Montenegro"},
    {"emoji": "🇲🇦", "countryName": "Morocco"},
    {"emoji": "🇳🇱", "countryName": "Netherlands"},
    {"emoji": "🇳🇿", "countryName": "New Zealand"},
    {"emoji": "🇳🇮", "countryName": "Nicaragua"},
    {"emoji": "🇳🇬", "countryName": "Nigeria"},
    {"emoji": "🇲🇰", "countryName": "North Macedonia"},
    {"emoji": "🇳🇴", "countryName": "Norway"},
    {"emoji": "🇴🇲", "countryName": "Oman"},
    {"emoji": "🇵🇰", "countryName": "Pakistan"},
    {"emoji": "🇵🇸", "countryName": "Palestine"},
    {"emoji": "🇵🇦", "countryName": "Panama"},
    {"emoji": "🇵🇾", "countryName": "Paraguay"},
    {"emoji": "🇵🇪", "countryName": "Peru"},
    {"emoji": "🇵🇭", "countryName": "Philippines"},
    {"emoji": "🇵🇱", "countryName": "Poland"},
    {"emoji": "🇵🇹", "countryName": "Portugal"},
    {"emoji": "🇶🇦", "countryName": "Qatar"},
    {"emoji": "🇷🇴", "countryName": "Romania"},
    {"emoji": "🇷🇺", "countryName": "Russia"},
    {"emoji": "🇸🇦", "countryName": "Saudi Arabia"},
    {"emoji": "🇷🇸", "countryName": "Serbia"},
    {"emoji": "🇸🇬", "countryName": "Singapore"},
    {"emoji": "🇸🇰", "countryName": "Slovakia"},
    {"emoji": "🇸🇮", "countryName": "Slovenia"},
    {"emoji": "🇿🇦", "countryName": "South Africa"},
    {"emoji": "🇰🇷", "countryName": "South Korea"},
    {"emoji": "🇪🇸", "countryName": "Spain"},
    {"emoji": "🇱🇰", "countryName": "Sri Lanka"},
    {"emoji": "🇸🇪", "countryName": "Sweden"},
    {"emoji": "🇨🇭", "countryName": "Switzerland"},
    {"emoji": "🇹🇼", "countryName": "Taiwan"},
    {"emoji": "🇹🇭", "countryName": "Thailand"},
    {"emoji": "🇹🇳", "countryName": "Tunisia"},
    {"emoji": "🇹🇷", "countryName": "Turkey"},
    {"emoji": "🇺🇦", "countryName": "Ukraine"},
    {"emoji": "🇦🇪", "countryName": "United Arab Emirates"},
    {"emoji": "🇬🇧", "countryName": "United Kingdom"},
    {"emoji": "🇺🇸", "countryName": "United States"},
    {"emoji": "🇺🇾", "countryName": "Uruguay"},
    {"emoji": "🇺🇿", "countryName": "Uzbekistan"},
    {"emoji": "🇻🇪", "countryName": "Venezuela"},
    {"emoji": "🇻🇳", "countryName": "Vietnam"},
    {"emoji": "🇾🇪", "countryName": "Yemen"},
    {"emoji": "🇿🇼", "countryName": "Zimbabwe"},
];

}
