// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAD3fnfz-w5rT_irKqI8X30W7PhEd3Rvo',
    appId: '1:888589068309:web:34ab0ec1f2e2cfd04c461c',
    messagingSenderId: '888589068309',
    projectId: 'qawl-io',
    authDomain: 'qawl-io.firebaseapp.com',
    storageBucket: 'qawl-io.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbiyzhKstUschpXHx7SxrdUxhsIjmho8',
    appId: '1:888589068309:android:2f2083f1141ad72c4c461c',
    messagingSenderId: '888589068309',
    projectId: 'qawl-io',
    storageBucket: 'qawl-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtG7PMk8v2D_53FoznPvyQEeu3dwmvZ9U',
    appId: '1:888589068309:ios:e29d15360d0c1a474c461c',
    messagingSenderId: '888589068309',
    projectId: 'qawl-io',
    storageBucket: 'qawl-io.appspot.com',
    iosBundleId: 'com.testing.qawl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtG7PMk8v2D_53FoznPvyQEeu3dwmvZ9U',
    appId: '1:888589068309:ios:c504dc5917b7fd474c461c',
    messagingSenderId: '888589068309',
    projectId: 'qawl-io',
    storageBucket: 'qawl-io.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );
}
