// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj9lpsIfAxOc9D6OCCsFfvifaVeSnHmCY',
    appId: '1:757975886517:web:e6b25f28c1c97520e5ecfc',
    messagingSenderId: '757975886517',
    projectId: 'qawl-io-8c4ff',
    authDomain: 'qawl-io-8c4ff.firebaseapp.com',
    storageBucket: 'qawl-io-8c4ff.appspot.com',
    measurementId: 'G-HXV6BZ7Q2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5F-pGaFugjp-gqEde1zVAg-8l7Jabbfs',
    appId: '1:757975886517:android:9c8d7145c262bccbe5ecfc',
    messagingSenderId: '757975886517',
    projectId: 'qawl-io-8c4ff',
    storageBucket: 'qawl-io-8c4ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEp19apz6tDNQiMR84XbONtJCZq0wvEqo',
    appId: '1:757975886517:ios:474cc9719bc0ba78e5ecfc',
    messagingSenderId: '757975886517',
    projectId: 'qawl-io-8c4ff',
    storageBucket: 'qawl-io-8c4ff.appspot.com',
    iosBundleId: 'com.testing.qawl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEp19apz6tDNQiMR84XbONtJCZq0wvEqo',
    appId: '1:757975886517:ios:690ae37b43d5e3a4e5ecfc',
    messagingSenderId: '757975886517',
    projectId: 'qawl-io-8c4ff',
    storageBucket: 'qawl-io-8c4ff.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );
}
